const firstDishes = {
    header: 'Первые блюда',
    products: [
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const secondDishes = {
    header: 'Вторые блюда',
    products: [
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const drinks = {
    header: 'Напитки',
    products: [
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const garnirs = {
    header: 'Гарниры',
    products: [
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная!',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const salats = {
    header: 'Гарниры',
    products: [
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const beer = {
    header: 'Пивная карта',
    products: [
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const snacks = {
    header: 'Закуски',
    products: [
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const brazier = {
    header: 'Блюда на мангале',
    products: [
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '../../../../img/advantage3.png',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const productsArray = [firstDishes, secondDishes, drinks, garnirs, salats, beer, snacks, brazier];

export default productsArray;
